import Head from "next/head";
import {
  ZkConnectButton,
  ZkConnectResponse,
  AuthType,
  useZkConnect,
  ZkConnectClientConfig,
} from "@sismo-core/zk-connect-react";
import { RainbowKit } from "../components/RainbowKit";
import { useState } from "react";
import { Vote } from "@/components/vote";
import Projects from "@/components/projects";
import { ZkConnect } from "@/components/zkConnectButton";

export default function Home() {
  const { responseBytes } = useZkConnect({
    config: {
      appId: "0x03e869be5fa809ca90f1b77a8e31b86f",
    },
  });

  return (
    <>
      <Head>
        <title>ZkAnon Vote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="relative flex h-16 items-center justify-between mt-5">
          <div className="text-xl font-bold">🥷 ZkAnonVote</div>
          <RainbowKit />
        </div>
        <Projects ZkConnect={ZkConnect} />
        {responseBytes && <Vote zkConnectRes={responseBytes} />}
      </main>
    </>
  );
}
